import 'src/styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Providers from './providers';
import { ReactNode } from 'react';
import Header from 'src/components/Header/Header';
import { AuthContextProvider } from 'src/context/Auth';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Funfy-forum',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <AuthContextProvider>
          <Header />
          <Providers>{children}</Providers>
        </AuthContextProvider>
      </body>
    </html>
  );
}
